//计数器
export const ACCOUNT_ADD = 'ACCOUNT_ADD'
export const ACCOUNT_REDUCTIVE = 'ACCOUNT_REDUCTIVE'
export const ACCOUNT_SAYNC_ADD = 'ACCOUNT_SAYNC_ADD'
export const ACCOUNT__SAYNC_REDUCTIVE = 'ACCOUNT__SAYNC_REDUCTIVE'
